### ISSUE TITLE
Customize notification icon

### ISSUE THREAD

**Issue by felinuxsas** [mradosta/cordova-plugin-streaming#3]
Hi,

I'm using this plugin successfully. I'd like to know how can I set my own icon for status bar and a custom bitmap for expanded notification (instead of music note).

Thanks in advance.

**Comment by mradosta** [comment]
Just replace the image as needed in the res/drawable folder. Check here:
https://github.com/mradosta/cordova-plugin-streaming/tree/master/src/android/res/drawable
