### ISSUE TITLE
Play/Pause/Stop button not appear on notification bar.

### ISSUE THREAD

**Issue by manusimpson** [mradosta/cordova-plugin-streaming#7]
I did a simple radio streaming player with this plugin and it works well but when I try to stop/pause the stream from notification bar it only show the X for close the notification, Play/Pause/Stop isn't showed.
![img_20170127_175531](https://cloud.githubusercontent.com/assets/3140904/22387422/59e8f860-e4ba-11e6-9d4f-d345b97d8b35.jpg)

Thanks in advance!

**Comment by felinuxsas** [comment]
I'm having the same issue. Additionally, the close button (x) doesn't work. App keeps open and notification doesn't disappear.

**Comment by manusimpson** [comment]
I've found the problem. The path to images are wrong in notifications xml files.
Replaces this 2 file in ./your-project/platforms/android/res/layout

[notification_xml_layout.zip](https://github.com/mradosta/cordova-plugin-streaming/files/984336/notification_xml_layout.zip)
